name: Android Debug Build
  
  on:
    workflow_dispatch:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Gradle Cache
          uses: actions/cache@v3
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
  
        - name: Verify project structure
          run: |
            echo "Verifying project structure..."
            if [ ! -d "android" ]; then
              echo "Missing 'android' directory. Ensure this is an Android or React Native project."
              exit 1
            fi
            if [ ! -f "package.json" ]; then
              echo "Missing 'package.json'. Ensure this is a React Native project."
              exit 1
            fi
            if [ ! -f "android/build.gradle" ]; then
              echo "Missing 'android/build.gradle'."
              exit 1
            fi
            echo "Project structure validated."
  
        - name: Install jq if needed
          run: |
            if ! command -v jq &> /dev/null; then
              echo "Installing jq..."
              sudo apt-get update && sudo apt-get install -y jq
            fi
  
        - name: Install Android SDK (cmdline-tools)
          run: |
            echo "Installing Android SDK..."
            mkdir -p android-sdk/cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
            unzip sdk.zip -d tmp-sdk
            mv tmp-sdk/cmdline-tools android-sdk/cmdline-tools/latest
            rm -rf tmp-sdk sdk.zip
            echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
            echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
            echo "$PWD/android-sdk/platform-tools" >> $GITHUB_PATH
            echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
  
        - name: Accept SDK licenses and install components
          run: |
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
            sdkmanager --update
  
        - name: Detect Node.js version from package.json
          id: detect-node
          run: |
            if [ -f "package.json" ]; then
              version=$(jq -r '.engines.node' package.json)
              if [ "$version" == "null" ] || [ -z "$version" ]; then
                echo "version=18" >> $GITHUB_OUTPUT
              else
                echo "version=$version" >> $GITHUB_OUTPUT
              fi
            else
              echo "version=18" >> $GITHUB_OUTPUT
            fi
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ steps.detect-node.outputs.version }}
  
        - name: Install npm dependencies
          run: |
            if [ -f "package-lock.json" ]; then
              npm ci
            else
              npm install
            fi
  
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'gradle'
  
        - name: Add compileSdkVersion if missing
          run: |
            if ! grep -q "compileSdkVersion" android/build.gradle; then
              echo "Adding compileSdkVersion = 33"
              sed -i '/ext {/a\        compileSdkVersion = 33' android/build.gradle
            fi
  
        - name: Generate Debug Keystore
          run: |
            if ! keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android > /dev/null 2>&1; then
              echo "Generating new debug key..."
              keytool -genkeypair \
                -v \
                -keystore android/app/debug.keystore \
                -alias androiddebugkey \
                -storepass android \
                -keypass android \
                -keyalg RSA \
                -keysize 2048 \
                -validity 10000 \
                -dname "CN=Android Debug,O=Android,C=US" \
                -deststoretype pkcs12
            fi
  
        - name: Build Debug APK
          run: ./gradlew assembleDebug -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m" --no-daemon
          working-directory: android
  
        - name: Upload APK artifact
          uses: actions/upload-artifact@v4
          with:
            name: debug-apk
            path: android/app/build/outputs/apk/debug/*.apk
            retention-days: 7
  