name: Pull Request Checks

on: 
  pull_request:
    branches: 
      - main
      - develop

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install Packages
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run TypeScript compiler
        run: yarn tsc --noEmit